### ISSUE TITLE
Error: Cannot find module '/usr/local/lib/node_modules/alfred-otter/dist/index.js'

### ISSUE THREAD

**Issue by atestu** [Stvad/alfred-otter#2]
Hi,

I just installed this great looking workflow using the npm command. I put in my email and password like instructed and using the debugger in Alfred I was able to see that it spits out an error:

```
Error: Cannot find module '/usr/local/lib/node_modules/alfred-otter/dist/index.js'
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

When I type otter it fails immediately and shows my default search engines for Alfred

**Comment by Stvad** [comment]
Hey! Apologies, I think the latest release may have been packaged improperly. Let me investigate and push out an update!

**Comment by Stvad** [comment]
Pushed out an update. run the same npm command to get the latest version!

**Comment by atestu** [comment]
Thank you! Unfortunately it still doesn't work (but I get a proper error, so this particular issue is fixed) because I have 2FA enabled for my account. Any way around that? I need 2FA to stay on.

**Comment by Stvad** [comment]
this relies on unofficial otter api https://github.com/omerdn1/otter.ai-api and so pretends to be a browser for the purposes of auth. I don't think there is a good way to integrate with 2FA atm 🙁
